[package]
name = "atomic-write"
version = "0.1.3"
authors = ["greg <gregory.mkv@gmail.com>"]
license = "MIT"
description = "Efficient atomic writes with replacement"
keywords = ["atomic", "fs", "write"]
edition = "2018"

[dependencies]
nix = "0.12.0"
